# Default Custom templates:
# <PLAYER> - player nickname
# <MAX_PLAYER> - maximum number of players
# <CURRENT_PLAYERS> - number of current players
# <SPACE> - space
chatMessage:
  connectText: "<RGB:1,1,1> [ <SPACE> <RGB:0.19,0.97,0.41> > <SPACE> <RGB:1,1,1> ] Player <SPACE> <RGB:0.19,0.56,0.97> < PLAYER> <SPACE> <RGB:1,1,1> connected to the server! (Players: <SPACE> <RGB:0.19,0.56,0.97> <CURRENT_PLAYERS> <RGB:1,1,1> / <RGB:0.19,0.56,0.97> <MAX_PLAYER> <RGB:1,1,1>)"
  disconnectText: "<RGB:1,1,1> [ <SPACE> <RGB:0.97,0.28,0.19> < <SPACE> <RGB:1,1,1> ] Player <SPACE> <RGB:0.19,0.56,0.97> < PLAYER> <SPACE> <RGB:1,1,1> has disconnected from the server! (Players: <SPACE> <RGB:0.19,0.56,0.97> <CURRENT_PLAYERS> <RGB:1,1,1> / <RGB:0.19,0.56,0.97> <MAX_PLAYER> <RGB:1,1,1>)"
  deathText: "<RGB:1,1,1> [ <SPACE> <RGB:0.96,0.97,0.19> ~ <SPACE> <RGB:1,1,1> ] Player <SPACE> <RGB:0.19,0.56,0.97> < PLAYER> <SPACE> <RGB:1,1,1> died in battle!"
  killText: "<RGB:1,1,1> [ <SPACE> <RGB:0.96,0.97,0.19> ~ <SPACE> <RGB:1,1,1> ] Player <SPACE> <RGB:0.19,0.56,0.97> < PLAYER> <SPACE> <RGB:1,1,1> died in a battle with <SPACE> <RGB:0.19,0.56,0.97> <PLAYER_ENEMY> <RGB:1,1,1>!"